### ISSUE TITLE
"function() { var f = 1; }" throws in FunctionScope.__isValidResolution

### ISSUE THREAD

**Issue by ajvincent** [eslint/eslint-scope#60]
Test case:
```javascript
#!/usr/bin/env node
"use strict";

const espree = require("espree");
const eslintScope = require('eslint-scope');

const source = `function A() { var f = 1; }`;
const ast = espree.parse(source);
eslintScope.analyze(ast);
```

Error:
```
/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/scope.js:711
        const bodyStart = this.block.body.range[0];
                                               ^
TypeError: Cannot read property '0' of undefined
    at FunctionScope.__isValidResolution (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/scope.js:711:48)
    at FunctionScope.__resolve (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/scope.js:357:19)
    at FunctionScope.__staticCloseRef (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/scope.js:294:19)
    at FunctionScope.__close (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/scope.js:336:22)
    at Referencer.close (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/referencer.js:129:68)
    at Referencer.visitFunction (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/referencer.js:261:14)
    at Referencer.FunctionDeclaration (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/referencer.js:557:14)
    at Referencer.Visitor.visit (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/esrecurse/esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/esrecurse/esrecurse.js:83:38)
    at Referencer.Program (/home/ajvincent/compiled/update-mgr/stacklizard/node_modules/eslint-scope/lib/referencer.js:429:14)

```

**Comment by mysticatea** [comment]
You need to pass the `range` option to espree.

```js
const ast = espree.parse(source, { range: true });
eslintScope.analyze(ast);
```

**Comment by ajvincent** [comment]
Ok, thank you.  Is it documented anywhere that eslint-scope needs this?

**Comment by ajvincent** [comment]
(I did test with that change and it works, thank you.)

**Comment by aladdin-add** [comment]
Closing this issue as it looks like the question has been answered. If you still need help, please send
a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://eslint.org/chat). Thanks!
