### ISSUE TITLE
Maximum call stack size exceeded when StaticBlock has additional `parentNode` property

### ISSUE THREAD

**Issue by sanex3339** [eslint/eslint-scope#85]
Hello.
I encounter that `ScopeAnalyzer.analyze` goes into infinity loop when `StaticBlock` node has any additional property containing its parent node, for example `parentNode` property. It can be reproduced if `childVisitorKeys` option is not set

Stack trace:
```
Error: RangeError: Maximum call stack size exceeded
    at new Map (<anonymous>)
    at new Scope (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/eslint-scope/dist/eslint-scope.cjs:505:20)
    at new ClassStaticBlockScope (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/eslint-scope/dist/eslint-scope.cjs:1084:9)
    at ScopeManager.__nestClassStaticBlockScope (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/eslint-scope/dist/eslint-scope.cjs:1304:33)
    at Referencer.StaticBlock (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/eslint-scope/dist/eslint-scope.cjs:1935:27)
    at Referencer.Visitor.visit (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/esrecurse/esrecurse.js:104:34)
    at Referencer.Visitor.visitChildren (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/esrecurse/esrecurse.js:83:38)
    at Referencer.Visitor.visit (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/esrecurse/esrecurse.js:107:14)
    at Referencer.Visitor.visitChildren (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/esrecurse/esrecurse.js:88:26)
    at Referencer.StaticBlock (/Users/sanex/WebstormProjects/javascript-obfuscator/node_modules/eslint-scope/dist/eslint-scope.cjs:1937:14)
    at ScopeAnalyzer.analyze (/Users/sanex/WebstormProjects/javascript-obfuscator/src/analyzers/scope-analyzer/ScopeAnalyzer.ts:91:23)
```

How to reproduce:
- open `tests/class-static-blocks.js`
- replace first before each on the following
```
 beforeEach(() => {
            ast = espree.parse("class C { static { var a; let b; const c = 1; function d(){} class e {} } }", { ecmaVersion: 13 });
            ast.body.parentNode = ast;
            ast.body[0].parentNode = ast.body;
            ast.body[0].body.parentNode = ast.body[0];
            ast.body[0].body.body[0].parentNode = ast.body[0].body;
            scopeManager = analyze(ast, { ecmaVersion: 13 });
            ({ globalScope } = scopeManager);
        });
```

**Comment by bradzacher** [comment]
This is working as expected.
If you don't provide visitor keys, then the fallback is to iterate the properties and visit each value.

There is no way the traversal algorithm can know you've added a custom property that should not be visited unless you use visitor keys to tell it that.

**Comment by sanex3339** [comment]
Ok, thank you for the explanation
